server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:30000/eureka

spring:
  application:
    name: category-service
  datasource:
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/chinchinne
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: backend
    password: backend
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: chinchinne
      username: backend
      password: backend

logging:
  level:
    org:
      hibernate:
        sql: off
      springframework:
        web: debug
        data:
          mongodb:
            core: debug
    sql: off
    jdbc: off
    jdbc.sqlonly: info
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off